Support creation of containers and test containers on the global namespace
lcobucci/di-builder pull request #517
Opened 2023-05-05 15:29 UTC by lgrossi

When creating a new build configuration without a namespace and adding later on a subnamespace to it (e.g. using getTestContainer() will add a subnamespace 'Test') the dumped file will have an invalid namespace '\Test' and that will make the di compiler fail.

![image](https://user-images.githubusercontent.com/34237492/236501701-47a45493-019c-4447-b862-25edac4148a5.png)

2023-05-05 19:35 UTC, lcobucci commented
@lgrossi believe you pushed too many unnecessary files 😅

2023-05-05 20:39 UTC, lgrossi commented
> @lgrossi believe you pushed too many unnecessary files 😅

Ops, it was so simple that I did it without checking git diff. Totally forgot about .idea 😅.

2023-05-07 17:55 UTC, lcobucci requested changes
Just a teeny tiny thing 👍

2023-05-07 17:55 UTC, lcobucci commented on .gitignore
> +/.idea
This should be in your global ignore file, not here.

2023-08-01 21:09 UTC, lcobucci approved these changes

2023-08-01 21:22 UTC, merged